version: 2

models:
  - name: spellcheck
    #    description: <markdown_string>
    config:
      enabled: true

  - name: material_counts_by_error_field
    #    description: <markdown_string>
    config:
      enabled: true
