version: '3.9'

networks:
  backend:
    driver: bridge

x-restart-policy: &restart-policy
  restart: unless-stopped

x-logging-config: &logging-config
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '100M'

services:
  nginx:
    container_name: metaqs-nginx
    image: nginx:stable-alpine
    <<: *restart-policy
    <<: *logging-config
    depends_on:
      - fastapi
      - yovisto
    environment:
      NGINX_HOST: "${NGINX_HOST}"
      ROOT_PATH: "/api"
    volumes:
      - ./nginx/nginx-ssl.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/gzip_params:/etc/nginx/gzip_params:ro
      - ../mkdocs/site:/usr/share/nginx/html/docs:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"

  certbot:
    <<: *restart-policy
    <<: *logging-config
    container_name: metaqs-certbot
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        trap exit TERM
        while :; do
          echo "renewing certs"
          certbot renew
          sleep 12h & wait $${!}
        done

  fastapi:
    container_name: metaqs-fastapi
    build:
      context: ./src/
      network: host
    image: docker.edu-sharing.com/projects/oeh-redaktion/edusharing-projects-oeh-redaktion-metaqs-api:dev
    <<: *restart-policy
    <<: *logging-config
    volumes:
      - ./:/tmp
      - .env:/app/.env
    environment:
      ROOT_PATH: "/api"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS:-*}"
      LOG_LEVEL: "${LOG_LEVEL:-20}"
      LOGGER: uvicorn
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL:-http://10.254.1.31:9200}"
      ELASTICSEARCH_TIMEOUT: 20
    networks:
      - backend


  yovisto:
    container_name: yovisto  # Container from https://github.com/openeduhub/meta-yovisto
    image: docker.edu-sharing.com/projects/oeh-redaktion/edusharing-projects-oeh-redaktion-yovisto:dev
    <<: *restart-policy
    <<: *logging-config
    environment:
      ROOT_PATH: "/yovisto"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS:-*}"
      LOG_LEVEL: "${LOG_LEVEL:-20}"
      LOGGER: uvicorn
      WANT_RETRAINING: "${WANT_RETRAINING:-true}"
    command: bash -c "uvicorn --host 0.0.0.0 --port 80 --reload main:app"
    expose:
      - 443
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/_ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 250s
    networks:
      - backend
