version: '3.9'

volumes:
  pg-data:

networks:
  backend:
  frontend:

x-restart-policy: &restart-policy
  restart: unless-stopped

x-logging-config: &logging-config
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '100M'

services:
  nginx:
    container_name: metaqs-nginx
    image: nginx:stable-alpine
    <<: *restart-policy
    <<: *logging-config
    depends_on:
      - fastapi
      - yovisto
    environment:
      NGINX_HOST: "${NGINX_HOST}"
      ROOT_PATH: "/api"
    volumes:
      - ./nginx/nginx-ssl.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/gzip_params:/etc/nginx/gzip_params:ro
      - ../mkdocs/site:/usr/share/nginx/html/docs:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
    networks: [ frontend ]
    ports:
      - "80:80"
      - "443:443"

  certbot:
    <<: *restart-policy
    <<: *logging-config
    container_name: metaqs-certbot
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        trap exit TERM
        while :; do
          echo "renewing certs"
          certbot renew
          sleep 12h & wait $${!}
        done

  fastapi:
    container_name: metaqs-fastapi
    build:
      context: ./src/
      network: host
    image: docker.edu-sharing.com/projects/oeh-redaktion/edusharing-projects-oeh-redaktion-metaqs-api:dev
    <<: *restart-policy
    <<: *logging-config
    volumes:
      - ./:/tmp
    environment:
      POSTGRES_HOST: postgres
      ROOT_PATH: "/api"
      API_VERSION: "${API_VERSION:-v1}"
      API_KEY: "${API_KEY:-openeduhub}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS:-*}"
      BACKGROUND_TASK_ANALYTICS_INTERVAL: "${BACKGROUND_TASK_ANALYTICS_INTERVAL:-0}"
      BACKGROUND_TASK_SEARCH_STATS_INTERVAL: "${BACKGROUND_TASK_SEARCH_STATS_INTERVAL:-0}"
      BACKGROUND_TASK_SEARCH_STATS_SLEEP_INTERVAL: "${BACKGROUND_TASK_SEARCH_STATS_SLEEP_INTERVAL:-0}"
      BACKGROUND_TASK_SPELLCHECK_INTERVAL: "${BACKGROUND_TASK_SPELLCHECK_INTERVAL:-0}"
      LOG_LEVEL: "${LOG_LEVEL:-debug}"
      LOGGER: uvicorn
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL:-http://10.254.1.31:9200}"
      ELASTICSEARCH_TIMEOUT: 20
      WEB_CONCURRENCY: 1
    networks:
      - backend
      - frontend


  yovisto:
    container_name: yovisto
    image: docker.edu-sharing.com/projects/oeh-redaktion/edusharing-projects-oeh-redaktion-yovisto:dev
    <<: *restart-policy
    <<: *logging-config
    ports:
      - "8082:8082"
    environment:
      ROOT_PATH: ""
      API_VERSION: "${API_VERSION:-v1}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS:-*}"
      LOG_LEVEL: "${LOG_LEVEL:-debug}"
      LOGGER: uvicorn
      WEB_CONCURRENCY: 1
    command: bash -c "uvicorn --host 0.0.0.0 --port 8082 --reload main:app"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/_ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - backend
