version: '3.9'

volumes:
  shared-nginx-run:

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  nginx:
    ports:
      - "443:443"
    volumes:
      - shared-nginx-run:/run
      - ./nginx/nginx-ssl.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ../mkdocs/site:/usr/share/nginx/html/docs:ro
      - shared-dbt-docs:/usr/share/nginx/html/dbt-docs:ro

  nginx_reloader:
    <<: *restart_policy
    container_name: metaqs-nginx-reloader
    image: nginx:stable-alpine
    depends_on:
      - nginx
      - certbot
    pid: service:nginx
    volumes:
      - shared-nginx-run:/run
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        while :; do
          sleep 6h & wait $${!}
          echo reloading
          nginx -s reload
        done

  certbot:
    <<: *restart_policy
    container_name: metaqs-certbot
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        trap exit TERM
        while :; do
          echo "renewing certs"
          certbot renew
          sleep 12h & wait $${!}
        done
