version: 2

models:
  - name: collections
#    description: <markdown_string>
    config:
      enabled: true
    columns:
      - { name: id, data_type: uuid }
      - { name: path, data_type: ltree }
      - { name: title, data_type: text }
      - { name: description, data_type: text }
      - { name: keywords, data_type: jsonb }
      - { name: taxon_id, data_type: jsonb }
      - { name: edu_context, data_type: jsonb }
      - { name: doc, data_type: jsonb }
      - { name: portal_id, data_type: uuid }
      - { name: portal_path, data_type: ltree }
      - { name: portal_depth, data_type: int }
      - { name: portal_title, data_type: text }
    post-hook:
      - "
        create index if not exists collections_path_idx
          on {{ target.schema }}.collections
            using gist (path gist_ltree_ops( siglen= 100))
        "

  - name: materials
    #    description: <markdown_string>
    config:
      enabled: true
    columns:
      - { name: id, data_type: uuid }
      - { name: title, data_type: text }
      - { name: description, data_type: jsonb }
      - { name: keywords, data_type: jsonb }
      - { name: taxon_id, data_type: jsonb }
      - { name: edu_context, data_type: jsonb }
      - { name: license, data_type: jsonb }
      - { name: object_type, data_type: text }
      - { name: ads_qualifier, data_type: text }
      - { name: learning_resource_type, data_type: jsonb }
      - { name: intended_enduser_role, data_type: jsonb }
      - { name: url, data_type: text }
      - { name: replication_source, data_type: text }
      - { name: replication_source_id, data_type: text }
      - { name: created, data_type: timestamp }
      - { name: modified, data_type: timestamp }
      - { name: doc, data_type: jsonb }

  - name: collection_material
    #    description: <markdown_string>
    config:
      enabled: true
    columns:
      - { name: material_id, data_type: uuid }
      - { name: collection_id, data_type: uuid }

  - name: pruned_resource_ids
    #    description: <markdown_string>
    config:
      enabled: true
      post-hook:
        - "
          delete
          from store.spellcheck
          where resource_id = any (
              select id from {{ target.schema }}.pruned_resource_ids
              )
          "

  - name: spellcheck_queue
    #    description: <markdown_string>
    config:
      enabled: true
    columns:
      - { name: resource_id, data_type: uuid }
      - { name: resource_type, data_type: resource_type }
      - { name: resource_field, data_type: resource_field }
      - { name: text_content, data_type: text }
      - { name: derived_at, data_type: timestamp }

  - name: missing_fields
    #    description: <markdown_string>
    config:
      enabled: true
    columns:
      - { name: resource_id, data_type: uuid }
      - { name: resource_type, data_type: resource_type }
      - { name: missing_field, data_type: resource_field }

  - name: collection_material_ext
    #    description: <markdown_string>
    config:
      enabled: true

  - name: material_counts
    #    description: <markdown_string>
    config:
      enabled: true

  - name: material_counts_by_missing_field
    #    description: <markdown_string>
    config:
      enabled: true

  - name: material_counts_by_learning_resource_type
    #    description: <markdown_string>
    config:
      enabled: true
