default_language_version:
    python: python3.7.4

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.7.4
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.8.4
#    hooks:
#      - id: flake8
#        args: [ "--max-line-length", "120" ]
#  - repo: https://github.com/jendrikseipp/vulture
#    rev: 'v2.3'  # or any later Vulture version
#    hooks:
#      - id: vulture
#  -   repo: https://github.com/asottile/dead
#      rev: v1.4.0
#      hooks:
#      -   id: dead
