name: MetaQS Action after merge to dev

on:
  push:
    branches:
      - combining_ci_cd
  pull_request:
    branches:
      - dev

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v1

  build-and-push-fastapi:
    name: Build and Push Docker image to community edu hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to edu sharing
        run: docker login community.docker.edu-sharing.com -u ${{ secrets.DOCKER_EDU_HUB_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_EDU_HUB_REGISTRY_PASSWORD }}

      - name: Build the container
        run: docker build -t community.docker.edu-sharing.com/metaqs-api-fastapi_dev:latest .

      - name: Push the Docker image
        run: docker push community.docker.edu-sharing.com/metaqs-api-fastapi_dev:latest
