name: MetaQS Action after merge to main

on:
  pull_request:
    branches:
      - main

env:
  docker_repository: "docker.edu-sharing.com"
  path_prefix: "/projects/wlo/edu_sharing-projects-wlo-metaqs-"
  image_tag: "latest"

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v1

  build-and-push-fastapi:
    name: Build and Push FastAPI image to community edu hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to edu sharing
        run: docker login ${{env.docker_repository}} -u ${{ secrets.DOCKER_EDU_HUB_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_EDU_HUB_REGISTRY_PASSWORD }}
      - name: Build
        run: docker build -t ${{env.docker_repository}}${{env.path_prefix}}api:${{env.image_tag}} ./src
      - name: Push
        run: docker push ${{env.docker_repository}}${{env.path_prefix}}api:${{env.image_tag}}
