name: MetaQS DBT Docker Image

on:
  push:
    branches:
      - *

jobs:
  build-dbt:
    name: Build Docker image to community edu hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the container
        run: docker build -t community.docker.edu-sharing.com/metaqs-dbt:latest ./dbt/Dockerfile
